### ISSUE TITLE
Home do projeto está na página de "Sofás"

### ISSUE THREAD

**Issue by LDinizz** [murillo94/stok-tok#1]
Ao acessar "https://stok-tok.vercel.app/" o site carrega a página de sofás. 

Ao navegar percebi que existe a aba "Explorar" onde mostra a categorias dos móveis.

https://prnt.sc/10b7gtb

**Comment by murillo94** [comment]
Oi @LDinizz, a ideia inicial era mostrar apenas o endpoint de sofás mesmo. Seria muito legal implementar uma busca geral dos produtos ao invés apenas do sofá na `home`.

Obrigado pela sugestão! O que acha te tentar implementar uma busca geral?
